# Generated by Django 4.0.6 on 2022-07-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ferreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_elemen', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.IntegerField()),
                ('precio_cos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mifamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_element', models.CharField(max_length=30)),
                ('referencia_pro', models.CharField(max_length=30)),
                ('cantidad_ven', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
