# Generated by Django 4.0.6 on 2022-07-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferreteria',
            options={'ordering': ('nombre_elemen', '-cantidad')},
        ),
        
    ]
